name: Docker Image CI

on:
    push:
        tags: ["*"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Extract variables
              id: variables
              run: |
                  echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/};
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}
            - name: Login to Container Registry
              uses: docker/login-action@v1
              with:
                  # registry: ghcr.io
                  username: ${{ secrets.REGISTRY_USER }}
                  password: ${{ secrets.REGISTRY_TOKEN }}
                  logout: true
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.REGISTRY_REPO }}:${{ steps.variables.outputs.SOURCE_TAG }}
                      ${{ secrets.REGISTRY_REPO }}:latest
                  platforms: |
                      linux/386
                      linux/amd64
                      linux/arm64/v8
                      linux/s390x
                      linux/ppc64le
                      linux/arm/v6
                      linux/arm/v7
